/// This file defines names for views in this project used as named routes.
/// These names are constant strings and should be defined in the format
///
/// ``` const String *viewName*ViewRoute = 'unique_route_name';  ```
const String homeRoute = '/home';
const String pre = '/pre';
const String logInRoute = '/logIn';
const String mainPage = '/mainPage';
const String inbox = '/inbox';
const String mentorProfile = '/mentorProfile';
const String internProfile = '/internProfile';
const String messagePage = '/messagePage';
const String reportPage = '/reportPage';
const String myProfile = '/myProfile';
const String editProfile = '/editProfile';
const String assignedInterns = '/assignedInterns';
const String otherMentors = '/otherMentors';
const String internInfo = '/internInfo';
const String blocker = '/blocker';
const String engagement = '/engagement';
const String report = '/report';
const String submit = '/submit';
const String resetPassword = '/resetPassword';
const String mainPageMentor = '/mainPageMentor';
const String homePageMentor = '/homePageMentor';
// const String edit = '/edit';
// const String submitted = '/submitted';
// const String help = '/help';
// const String wallet = '/wallet';
// const String addCard = '/addCard';
// const String editCard = '/editCard';
// const String fund = '/fund';
// const String completedOrder = '/completedOrder';
// const String menuPage = '/menuPage';
// const String mealSearch = '/mealSearch';
// const String kitchenPage = '/kitchenPage';
// const String termsAndConditions = '/termsAndConditions';
// const String miniCartPage = '/miniCartPage';
// const String cart = '/cart';
// const String checkOut = '/checkOut';
// const String paymentScreen = '/paymentScreen';
// const String checkOutBack = '/checkOutBack';
// const String checkOutPageWithCoupon = '/checkOutPageWithCoupon';
// const String checkOutPageWithCouponModel = '/checkOutPageWithCouponModel';
// const String orderSuccessful = '/orderSuccessful';
// const String settingsRoute = '/settingsRoute';